default:
  $formatter: 'Haskel\MapSerializer\Formatter\DatetimeFormatter'

datetime:
  $formatter: 'Haskel\MapSerializer\Formatter\DatetimeFormatter'

date:
  $formatter: 'Haskel\MapSerializer\Formatter\DatetimeFormatter'

time:
  $formatter: 'Haskel\MapSerializer\Formatter\DatetimeFormatter'