default:
  $formatter: 'Haskel\MapSerializer\Formatter\DatetimeFormatter'

string:
  $formatter: 'Haskel\MapSerializer\Formatter\DatetimeFormatter'

int:
  $formatter: 'Haskel\MapSerializer\Formatter\DatetimeFormatter'

time:
  $formatter: 'Haskel\MapSerializer\Formatter\DatetimeFormatter'